spring:
  config:
    activate:
      on-profile: prd

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/mydb?currentSchema=public
    username: myuser
    password: mypassword
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
logging:
  level:
    root: INFO
    org.springframework.boot.context.config: DEBUG
    com.grupo.gymSys: DEBUG
